#
# -*- coding: utf-8 -*-
"""firmata_test_3_18_19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15TGmCmLTn5gkujUXdemXobQZoy_62WtO
"""

import sys
import math as math
import platform

import inputs
import time

from rover import Rover

port = '/dev/ttyACM0' if platform.system() == "Linux" else '/dev/cu.usbmodem1411' 

rover = Rover(port, 3,5) 

#rover.set_port_pins()


def processInput(events):
    for event in events:
        print ('event.code',event.code, '\tevent.state',event.state)
        """
        directional pad up is forward, let off direction pad is stop
        """
        if event.code == 'ABS_Y' and event.state == 0:
            rover.drive(20)
        if event.code == 'ABS_Y' and event.state == 255:
            rover.drive(-20)
        if event.code == 'ABS_Y' and event.state == 127:
            labrat.drive(0)
        if event.code == 'ABS_X' and event.state == 0:
            labrat.turn(-1)
        if event.code == 'ABS_X' and event.state == 255:
            labrat.turn(1)
        if event.code == 'ABS_X' and event.state == 127:
            labrat.turn(0)

if __name__ == "__main__":
    rover = Rover(port, 3,5) 
    rover.set_port_pins()
    while True:
#        print("battery: ", rover.readBattery())
        events = inputs.get_gamepad()
        # processInput(events)
        for event in events:
            print ('event.code',event.code, '\tevent.state',event.state)
            """
            directional pad up is forward, let off direction pad is stop
            """
            if event.code == 'ABS_Y' and event.state == 0:
                rover.drive(20)
                #print('Move forward')
            if event.code == 'ABS_Y' and event.state == 255:
                rover.drive(-20)
                #print('Move backward')    
            if event.code == 'ABS_Y' and event.state == 127:
                rover.drive(0)
                #print('Move stop')    
            if event.code == 'ABS_X' and event.state == 0:
                rover.turn(-1)
                #print('Move left')    
            if event.code == 'ABS_X' and event.state == 255:
                rover.turn(1)
                #print('Move right')    
            if event.code == 'ABS_X' and event.state == 127:
                rover.turn(0)
                #print('Move 0')
            